version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5454:5454"
    environment:
      - PORT=5454
      - JWT_SECRET_KEY=Yukirinkawaii123!
    volumes:
      - .:/usr/src/app
    restart: always
